# Numpy


In [ ]:
# Import the numpy library as np

import numpy as np

In [7]:
# Create a numpy array with the elements [1, 2, 3, 4, 5]

arr = np.array([1, 2, 3, 4, 5])

print(arr.mean())
print(arr.max())
print(arr.min())

3.0
5
1


In [11]:
# Create a numpy array with the elements 1 to 100.

hundreds_arr = np.arange(1, 100+1, 1)
hundreds_arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
# Print the shape of the array from the previous step

hundreds_arr.shape

(100,)

In [14]:
np.ndim(hundreds_arr)

1

In [18]:
# Create a 2x2 numpy array with elements
# |1, 2|
# |3, 4|

arr_2x2 = np.array([[1, 2], [3, 4]])
print(arr_2x2)
print("-"*50)
print(arr_2x2.shape)
print("-"*50)
print(np.ndim(arr_2x2))

[[1 2]
 [3 4]]
--------------------------------------------------
(2, 2)
--------------------------------------------------
2


In [21]:
# Calculate the sum of all elements in the 2x2 array

print(np.sum(arr_2x2))
print("-"*50)
print(arr_2x2.sum(axis=0))
print("-"*50)
print(arr_2x2.sum(axis=1))

10
--------------------------------------------------
[4 6]
--------------------------------------------------
[3 7]


In [22]:
# Calculate the mean of the elements in the 2x2 array
print(arr_2x2)
print("-"*50)
print(arr_2x2.mean(axis=0))
print("-"*50)
print(arr_2x2.mean(axis=1))

[[1 2]
 [3 4]]
--------------------------------------------------
[2. 3.]
--------------------------------------------------
[1.5 3.5]


In [29]:
# Reshape the 2x2 array to a 1x4 array and print it

print(arr_2x2.reshape(1, 4))
print("-"*50)
print(arr_2x2.reshape(1, 4).shape)
print("-"*50)
print(np.ndim(arr_2x2.reshape(1, 4)))

[[1 2 3 4]]
--------------------------------------------------
(1, 4)
--------------------------------------------------
2


In [30]:
print(arr_2x2.reshape(4, 1))
print("-"*50)
print(arr_2x2.reshape(4, 1).shape)
print("-"*50)
print(np.ndim(arr_2x2.reshape(4, 1)))

[[1]
 [2]
 [3]
 [4]]
--------------------------------------------------
(4, 1)
--------------------------------------------------
2


In [36]:
arr2 = np.arange(1, 5, 1)
print(arr2)
print(arr2.shape)
print(np.ndim(arr2))

print("-"*50)

arr3 = arr2.reshape(2, 2)
print(arr3)
print(arr3.shape)
print(np.ndim(arr3))

print("-"*50)

arr4 = arr3.reshape(4, 1)
print(arr4)
print(arr4.shape)
print(np.ndim(arr4))

[1 2 3 4]
(4,)
1
--------------------------------------------------
[[1 2]
 [3 4]]
(2, 2)
2
--------------------------------------------------
[[1]
 [2]
 [3]
 [4]]
(4, 1)
2


In [37]:
my_list = []

for row in arr4:
    for elm in row:
        my_list.append(elm)

arr5 = np.array(my_list)

print(arr5)
print(arr5.shape)
print(np.ndim(arr5))

[1 2 3 4]
(4,)
1
